source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'pop', '~> 1.0'
pod 'AsyncDisplayKit'
pod 'KVOController'
pod 'RZTransitions', '~> 1.0'
pod 'UICKeyChainStore'
pod 'GPUImage'
pod 'SDWebImage', '~>3.6'
pod 'Shimmer'
pod 'Tweaks'
pod 'RESideMenu', '~> 4.0.7'